### ISSUE TITLE
你好，我将requirements文件copy到colab后，运行!pip3 install -r  /content/requirements.txt，出现了如下错误，请帮忙，谢谢。

### ISSUE THREAD

**Issue by huowa2298** [ultrasev/stream-whisper#10]
Building wheels for collected packages: PyAudio, webrtcvad, faster-whisper
  error: subprocess-exited-with-error
  
  × Building wheel for PyAudio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for PyAudio (pyproject.toml) ... error
  ERROR: Failed building wheel for PyAudio
  Building wheel for webrtcvad (setup.py) ... done
  Created wheel for webrtcvad: filename=webrtcvad-2.0.10-cp310-cp310-linux_x86_64.whl size=73465 sha256=f69cc565de2fb14351556dbae3035362e38df81be565e7495380f7cd7a117f89
  Stored in directory: /root/.cache/pip/wheels/2a/2b/84/ac7bacfe8c68a87c1ee3dd3c66818a54c71599abf308e8eb35
  Building wheel for faster-whisper (setup.py) ... done
  Created wheel for faster-whisper: filename=faster_whisper-0.10.0-py3-none-any.whl size=1539726 sha256=b9e57aeb0f7a805f9530a5b9e5fbe8208d0633f1329158df96eb8836f3962378
  Stored in directory: /root/.cache/pip/wheels/b3/4e/9a/bd36d2645cb73f909a3a65a2e317fec5c6a79c8121ab9eb42f
Successfully built webrtcvad faster-whisper
Failed to build PyAudio
ERROR: Could not build wheels for PyAudio, which is required to install pyproject.toml-based projects

**Comment by ultrasev** [comment]
@huowa2298 你是什么操作系统？ windows ?

**Comment by ultrasev** [comment]
这个包安装了吗？ `apt -y install portaudio19-dev`

**Comment by huowa2298** [comment]
多谢了，用了“apt -y install portaudio19-dev”后好了，我是用谷歌colab来做的，新手很多不懂，多谢赐教

**Comment by huowa2298** [comment]
请问用colab时如何找到.env文件？我运行/content/stream-whisper/src/config.py会出错，在loadenv（）时出现“Flase”错误，如何解决？谢谢。

**Comment by ultrasev** [comment]
@huowa2298 .env 是为了存一点敏感信息，比如 redis 服务地址，这个您配置了吗？
如果有 redis ，比如  redis://xxxx:xxx@:6379，你可以在 colab 里执行
`!echo redis://xxxx:xxx@:6379 > .env` 
即可
