### ISSUE TITLE
代码里面没有 .env 文件

### ISSUE THREAD

**Issue by suocean16** [ultrasev/stream-whisper#12]
问题1 ：不知道在哪里找 .env 文件。 

问题2： 你说 redis 地址不是必须的。 那么用它来做什么？ 如何替代？

**Comment by ultrasev** [comment]
@suocean16 
问题2： 因为录音是在本地录的，比如家里的笔记本，而转写是在colab上，所以得把本地的音频同步给 colab 上的 whisper 模型，redis 就是用来同步这个音频数据的。其他方案也可以，比如，如果你有一个带公网 IP 的服务器来运行 whisper，你也可以直接起一个 http 服务，来接收本地发送过去的音频数据。 

问题1： .env 一般用于管理环境变量，通常存放的是一些敏感信息，所以你需要自已创建配置 .env 文件。比如我的 .env ：
<img width="1271" alt="image" src="https://github.com/ultrasev/stream-whisper/assets/51262739/772366cb-63f9-4317-8789-c383640969a5">

如果你没有 redis 服务实例，可以参考我之前的视频在 redislabs 上免费注册一个。https://www.bilibili.com/video/BV1DJ4m1s7Jw/

**Comment by suocean16** [comment]
非常感谢！
