### ISSUE TITLE
Python环境依赖的问题和模型删除的问题

### ISSUE THREAD

**Issue by frisk0926** [ultrasev/stream-whisper#15]
1.Could not load library cudnn_ops_infer64_8.dll. Error code 126
Please make sure cudnn_ops_infer64_8.dll is in your library path!
在网上找依赖包的添加教程时很模糊，能否指点一下

2.之前在本地电脑上下载过large v3的model 如何把他删除掉呢

**Comment by frisk0926** [comment]
上述的第一个问题已解决，第二个问题未解决

**Comment by ultrasev** [comment]
> 上述的第一个问题已解决，第二个问题未解决

@frisk0926 Model 一般缓存到用户目录下面了，可以在 `~/.cache/whisper/` 下面看看，有 .pt 文件应该就是模型了。

**Comment by frisk0926** [comment]
> > 上述的第一个问题已解决，第二个问题未解决
> 
> @frisk0926 Model 一般缓存到用户目录下面了，可以在 `~/.cache/whisper/` 下面看看，有 .pt 文件应该就是模型了。

我只找到了这两个类似于把模型型号分开的wen文件夹    （左一）
这是否是缓存文件  能否直接删除呢（右一）

**Comment by frisk0926** [comment]
![QQ截图20240311083634](https://github.com/ultrasev/stream-whisper/assets/129162725/0133b7e6-7073-4ce4-a9b9-41a41d59dd7d)

**Comment by ultrasev** [comment]
可以，这个是从 huggingface 上缓存下来的模型及配置，删除了没有影响，就是下次使用是需要再次缓存。

**Comment by frisk0926** [comment]
> 可以，这个是从 huggingface 上缓存下来的模型及配置，删除了没有影响，就是下次使用是需要再次缓存。

清楚了。我在切换模型的时候发现，即使我没有用魔法预先从huggingface中下载对应的模型（只下载了base，其他没有下载），但在本地切换模型执行的时候，仍然可以运行，是因为他发现没有对应模型会自动替换别的吗？

**Comment by ultrasev** [comment]
@frisk0926  应该不会自动切换，有可能是没有删干净？ 这是我的 .cache/huggingface/ 下的模型（图1），我删除  `large-v3` 之后，再运行就需要从 Huggingface 上再次缓存 （图2）： 

<img width="1416" alt="image" src="https://github.com/ultrasev/stream-whisper/assets/51262739/f8a8676c-39cf-48aa-86a2-223ea53599b1">

<img width="1912" alt="image" src="https://github.com/ultrasev/stream-whisper/assets/51262739/e331ee1e-e948-4c83-8767-e4f2e045a6a9">

**Comment by frisk0926** [comment]
> @frisk0926 应该不会自动切换，有可能是没有删干净？ 这是我的 .cache/huggingface/ 下的模型（图1），我删除 `large-v3` 之后，再运行就需要从 Huggingface 上再次缓存 （图2）：
> 
> <img alt="image" width="1416" src="https://private-user-images.githubusercontent.com/51262739/311557872-f8a8676c-39cf-48aa-86a2-223ea53599b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMTk4OTUsIm5iZiI6MTcxMDExOTU5NSwicGF0aCI6Ii81MTI2MjczOS8zMTE1NTc4NzItZjhhODY3NmMtMzljZi00OGFhLTg2YTItMjIzZWE1MzU5OWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDAxMTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNzBkMDg3MGE2N2FjNDJkZDMyOTliYWEyOTFjNWU3MjE0NTU4YjY0NjYwMTg2ZDkzNmEyNWZkMWY4NGRjZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eG5OhmhGo_9z35_s-A8F7QUC_-f_mhWTZrSuWowX8Lc"> <img alt="image" width="1912" src="https://private-user-images.githubusercontent.com/51262739/311557822-e331ee1e-e948-4c83-8767-e4f2e045a6a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMTk4OTUsIm5iZiI6MTcxMDExOTU5NSwicGF0aCI6Ii81MTI2MjczOS8zMTE1NTc4MjItZTMzMWVlMWUtZTk0OC00YzgzLTg3NjctZTRmMmUwNDVhNmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDAxMTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YWE4MjU0NWI4YWMxNmUzMThjYjlmMWNhYzUyMGM0ZWUwMmEyN2FkMmUzOWFjNjNiYjJkNjJhNmU4MjUyOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EUFmXgyjvkU5f0aHuJNIZtZCXRxw_FY2onQN2BwuRho">

搞清楚了，因为马虎看错了地方，把模型填到类里去了  哈哈
