### ISSUE TITLE
安装apt -y install libcublas11 之后还出现了错误

### ISSUE THREAD

**Issue by josangmi** [ultrasev/stream-whisper#18]
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory

需要重启机器？

**Comment by josangmi** [comment]
安装 conda install -c conda-forge cudnn 解决。中间还装了个sudo apt install nvidia-cudnn，没成功 ，仅作参考。

**Comment by GaoangLiu** [comment]
@josangmi 这么快，正想回复你呢。感谢提供思路。

> 安装 conda install -c conda-forge cudnn 解决。中间还装了个sudo apt install nvidia-cudnn，没成功 ，仅作参考。

**Comment by josangmi** [comment]
感谢感谢。
