### ISSUE TITLE
请不吝点赞 订阅 转发 打赏支持明镜与点点栏目 这个怎么解决的？

### ISSUE THREAD

**Issue by josangmi** [ultrasev/stream-whisper#19]
请不吝点赞 订阅 转发 打赏支持明镜与点点栏目
请不吝点赞 订阅 转发 打赏支持明镜与点点栏目

**Comment by ultrasev** [comment]
@josangmi 😃 这个我也遇到过，估计是用了 YouTube 上的中文视频做了训练，特别是遇到静音内容时，会无中生有，转出来这种乱七八糟的东西。 我目前的办法是在转写结果上加个过滤，遇到这种结果就不输出。

再或者是用 large-v3 模型，这个应该稳定些。

**Comment by josangmi** [comment]
我发现Openai 自己的语音对话也会返回这个，笑死了。 只能硬来了

**Comment by josangmi** [comment]
3.11 也是可以用的
简单处理下就行。 其他没啥。
1. 重新安装redis包
pip uninstall aioredis;
pip install "redis>=4.2.0rc1";

2. 重新导入redis包
将 import aioredis
改为 from redis import asyncio as aioredis 
redis.asyncio和aioredis用法相同，项目代码不用更改

**Comment by GaoangLiu** [comment]
> 3.11 也是可以用的 简单处理下就行。 其他没啥。
> 
> 1. 重新安装redis包
>    pip uninstall aioredis;
>    pip install "redis>=4.2.0rc1";
> 2. 重新导入redis包
>    将 import aioredis
>    改为 from redis import asyncio as aioredis
>    redis.asyncio和aioredis用法相同，项目代码不用更改

@josangmi 👍

**Comment by ultrasev** [comment]
@josangmi 新更新的代码加了 whisper 自带的 VAD，极大减少了误转的情况 。可以试试。
