### ISSUE TITLE
readme中的描述有错误

### ISSUE THREAD

**Issue by muzian666** [ultrasev/stream-whisper#2]
如题，readme中说 `.env` 中的 `REDIS_URL` 应该修改为 `REDIS_SERVER`，或者将`src/config.py`中的`os.getenv('REDIS_SERVER')`修改为`os.getenv('REDIS_URL')`，不然会一直提示找不到URL

另外，建议可以加一个python的版本要求，`aioredis`包目前仍然不支持python3.11，使用python3.11会出现`duplicate base class TimeoutError`，建议使用python3.9或3.10

**Comment by ultrasev** [comment]
@muzian666 已修正，多谢提示。
