### ISSUE TITLE
client启动问题

### ISSUE THREAD

**Issue by xzqxnet0990** [ultrasev/stream-whisper#21]
请问启动client后会出现以下错误，这是因为没有声卡？
![image](https://github.com/ultrasev/stream-whisper/assets/51184271/f0827a4c-616b-4ecf-91dd-c4bf7d938dcd)
查看声卡，确实是有的
![image](https://github.com/ultrasev/stream-whisper/assets/51184271/4f4c9715-8556-441e-acfc-e7575f7cae34)

**Comment by GaoangLiu** [comment]
@xzqxnet0990 这种倒没有遇到过，重装一下驱动试试？ https://unix.stackexchange.com/questions/445386/pulseaudio-server-connection-failure-connection-refused-debian-stretch
