### ISSUE TITLE
程序异常退出

### ISSUE THREAD

**Issue by 1Wayne1** [ultrasev/stream-whisper#25]
![Snipaste_2024-05-08_22-12-18](https://github.com/ultrasev/stream-whisper/assets/49175665/ac840bbd-2de2-45af-8522-e3d538e10fc7)
程序运行时崩溃，我的cuda版本为11.7

**Comment by ultrasev** [comment]
有其他报错信息吗？

**Comment by 1Wayne1** [comment]
> 有其他报错信息吗？

没有，你用的cuda版本是多少？faster-whisper版本还是0.10.0吗？我在faster-whisper项目中发现有人跟我一样的问题，但没找到解决办法

**Comment by ultrasev** [comment]
我是用cpu运行的，没用cuda。`faster-whisper==0.10.0` ，你把device 改成 cpu 看看能跑不，确定一下是不是cuda的问题。
<img width="1184" alt="image" src="https://github.com/ultrasev/stream-whisper/assets/51262739/a27aa9a4-b7fe-490d-9fbe-29c4a4aff379">

**Comment by 1Wayne1** [comment]
> 我是用cpu运行的，没用cuda。`faster-whisper==0.10.0` ，你把device 改成 cpu 看看能跑不，确定一下是不是cuda的问题。 <img alt="image" width="1184" src="https://private-user-images.githubusercontent.com/51262739/328936904-a27aa9a4-b7fe-490d-9fbe-29c4a4aff379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODA0ODMsIm5iZiI6MTcxNTE4MDE4MywicGF0aCI6Ii81MTI2MjczOS8zMjg5MzY5MDQtYTI3YWE5YTQtYjdmZS00OTBkLTlmYmUtMjljNGE0YWZmMzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE0NTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhOTVmNjkzY2MyNDkxMjVkNjQzNWY1Zjg3YjlkNmYzMDYzZTg4MDQ4MjdjOTBjZTlhYzg1ODU0NGI2N2ZhMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yFu-C_Ka30OnYm9gfvdRMVUdSZwQMTCsNMu6mZMOqPQ">

cpu可以跑

**Comment by ultrasev** [comment]
用的什么模型，large?，gpu 什么型号，有没有可能显存占用过多？

**Comment by 1Wayne1** [comment]
> 用的什么模型，large?，gpu 什么型号，有没有可能显存占用过多？

应该就是cuda或者torch的问题。模型我从大到小都试过了，都会出错
显卡是3060ti 8G显存

**Comment by 1Wayne1** [comment]
[SYSTRAN/faster-whisper#71](https://github.com/SYSTRAN/faster-whisper/issues/71)
这是我看到的原项目中的讨论，看样子是还没找到原因在哪

**Comment by 1Wayne1** [comment]
问题解决了，我用这条命令重装了pytorch
`conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia`

**Comment by ultrasev** [comment]
重装大法好。
