### ISSUE TITLE
下载包出现错误

### ISSUE THREAD

**Issue by frisk0926** [ultrasev/stream-whisper#3]
在下载库的时候，出现下载错误：
Building wheel for webrtcvad (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      copying webrtcvad.py -> build\lib.win-amd64-cpython-39
      running build_ext
      building '_webrtcvad' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for webrtcvad
  Running setup.py clean for webrtcvad
Failed to build webrtcvad
ERROR: Could not build wheels for webrtcvad, which is required to install pyproject.toml-based projects

**Comment by ultrasev** [comment]
如错误提示，尝试升级一下 Microsoft Visual C++ 版本，然后再安装一下试试。

**Comment by frisk0926** [comment]
好的 我试一下

**Comment by frisk0926** [comment]
我就是b站评论区的那个粉丝  up有时间可以出一期全程部署的教程嘛  整个流程过一遍的那种  哈哈  小白弄着有点困难

**Comment by ultrasev** [comment]
> 我就是b站评论区的那个粉丝 up有时间可以出一期全程部署的教程嘛 整个流程过一遍的那种 哈哈 小白弄着有点困难

@frisk0926 可以，等我有时间出一个。

**Comment by muzian666** [comment]
up开个wiki吧，这样大家也能有点贡献
