### ISSUE TITLE
代码执行疑问

### ISSUE THREAD

**Issue by frisk0926** [ultrasev/stream-whisper#4]
apt -y install portaudio19-dev
这一句linux的命令在windows的vscode怎么执行呢，我想在vscode上执行客户端的代码

**Comment by ultrasev** [comment]
@frisk0926 windows 下不安装这个，直接 pip3 install pyaudio 看看能运行不？https://pypi.org/project/PyAudio/

**Comment by muzian666** [comment]
按照pyaudio的要求，可以用这个代码安装pyaudio: `python -m pip install pyaudio` 建议在虚拟环境中安装尝试
