### ISSUE TITLE
Kaggle的疑问

### ISSUE THREAD

**Issue by frisk0926** [ultrasev/stream-whisper#5]
![(G~90TW%ALC95V97C$%2BVJ](https://github.com/ultrasev/stream-whisper/assets/129162725/1a15d956-8106-4a91-b504-e5540253f50b)
为啥右边没有更换GPU加速的那个Accelerator加速的框框呢

**Comment by ultrasev** [comment]
<img width="335" alt="image" src="https://github.com/ultrasev/stream-whisper/assets/51262739/5a34d1c3-88eb-42f6-9ccf-c1b76ba4dba2">
手机号验证一下就有了。
