### ISSUE TITLE
你好，客户端是不是做成http:get或post请求,给mcu调用，如ESP32,STM32,这样会不会更有意思，反应速度提高了，MCU减轻了负担，你觉得呢？

### ISSUE THREAD

**Issue by gzlwz** [ultrasev/stream-whisper#6]
你好，客户端是不是做成http:get或post请求,给mcu调用，如ESP32,STM32,这样会不会更有意思，反应速度提高了，MCU减轻了负担，你觉得呢？

**Comment by ultrasev** [comment]
单片机相关的吗？这个我倒没有接触过，如果客户端能够加速音频的获取，那反应速度确实可以提高。

**Comment by muzian666** [comment]
我觉得延迟大小主要还是在服务端的处理能力和网络延迟上，一味的提高客户端的灵敏度并不能提高反应速度

**Comment by frisk0926** [comment]
> 你好，客户端是不是做成http:get或post请求,给mcu调用，如ESP32,STM32,这样会不会更有意思，反应速度提高了，MCU减轻了负担，你觉得呢？
对的  楼上大佬说的没错 确实是减轻了mcu的负担   避免在arduino或micropython上再写软件的代码了  但是延迟主要存在于客户端与服务端之间的联系延迟上  而且另一个问题是  esp32和stm32都跑不了pyaudio  除非在树莓派上  如果录音不使用python的原始库，用麦克风模块去录制的话  还是会很慢

**Comment by frisk0926** [comment]
> 你好，客户端是不是做成http:get或post请求,给mcu调用，如ESP32,STM32,这样会不会更有意思，反应速度提高了，MCU减轻了负担，你觉得呢？


对的  楼上大佬说的没错 确实是减轻了mcu的负担   避免在arduino或micropython上再写软件的代码了  但是延迟主要存在于客户端与服务端之间的联系延迟上  而且另一个问题是  esp32和stm32都跑不了pyaudio  除非在树莓派上  如果录音不使用python的原始库，用麦克风模块去录制的话  还是会很慢

**Comment by frisk0926** [comment]
还是建议用一些其他架构MCU的板子来构建类似语音助手的项目，esp32和ST的板子都不太适合实际应用，适合用来DIY

**Comment by ultrasev** [comment]
wiki 已开，各位。
