### ISSUE TITLE
数据传输协议的问题

### ISSUE THREAD

**Issue by frisk0926** [ultrasev/stream-whisper#7]
项目的数据传输是不是只有音频数据的传输，博主提到的通过Redis的数据传输有什么独特的优点嘛，没用过不是很清楚，其他协议像socket或mqtt协议可以胜任项目里的数据传输的操作嘛

**Comment by ultrasev** [comment]
使用 redis 是因为这种实现方法可能要用到消费机制，比如短时间内发过去 10 个音频片段，whisper 处理不完， 只能先存下来。而且这 10 条需要按顺序逐个处理，不然文本就乱了，redis 的阻塞队列可以实现这个功能。  

socket这种我不是很熟悉，但如果能连续接收多个音频，并且能顺序让 whisper 转写，我觉得也是可以的。

**Comment by ultrasev** [comment]
还有一个原因是，我想把录制文件与数据传输做成异步的，两者不干扰，各干各的，尽可能降低延迟。 @frisk0926

**Comment by frisk0926** [comment]
了解了
