### ISSUE TITLE
env环境问题

### ISSUE THREAD

**Issue by frisk0926** [ultrasev/stream-whisper#8]
当我在vscode中正常调用.env文件里的变量时会显示错误，而在pycharm中正常调用则不会
在vscode中使用txt的格式之后则不会出错，但是使用env格式就会出错
![1706888188737](https://github.com/ultrasev/stream-whisper/assets/129162725/10add1a4-d8bf-42c6-a76f-7cfdc52f28ab)
是因为在vscode缺少了env的什么插件的原因嘛

**Comment by ultrasev** [comment]
.env 为了配置环境变量，其实你直接把 redis_server 写到 config.py 中也可以，注意别外泄。 @frisk0926 


```python
REDIS_SERVER="your redis server"
```

或者你把 `.env` 改成绝对路径，比如 `d:/faster whisper/....` ，注意路径中里有空格，需要转义。

**Comment by frisk0926** [comment]
了解
