### ISSUE TITLE
Kaggle平台环境配置和库安装问题

### ISSUE THREAD

**Issue by frisk0926** [ultrasev/stream-whisper#9]
在运行时出现了如下报错，似乎是Library libcublas.so.11 is not found or cannot be loaded

之前我执行了sudo apt-get install libcublas-11-0，但并不作用
![1706924248080](https://github.com/ultrasev/stream-whisper/assets/129162725/cbf63402-bcae-457e-a53b-b30ef3769140)

**Comment by frisk0926** [comment]
是否需要先安装cuda toolkit安装包  然后再进行安装呢

**Comment by ultrasev** [comment]
@frisk0926 可以把你的 Kaggle notebook 分享出来吗？我一会儿试试。

**Comment by ultrasev** [comment]
> 是否需要先安装cuda toolkit安装包 然后再进行安装呢

@frisk0926 默认应该已经装好 CUDA 了。

**Comment by frisk0926** [comment]
> @frisk0926 可以把你的 Kaggle notebook 分享出来吗？我一会儿试试。

好的稍等

**Comment by frisk0926** [comment]
> > 是否需要先安装cuda toolkit安装包 然后再进行安装呢
> 
> @frisk0926 默认应该已经装好 CUDA 了。

![1706924686844](https://github.com/ultrasev/stream-whisper/assets/129162725/9cd096af-bb3f-46b6-bf2d-bddf46427c17)
y有可能和版本有关吗

**Comment by frisk0926** [comment]
> @frisk0926 可以把你的 Kaggle notebook 分享出来吗？我一会儿试试。

设置为public之后把链接分享给你即可吗，stream-whisper文件夹改名为了whisper放在了根目录下
https://www.kaggle.com/code/friskjane/notebooke81877bb6f

**Comment by ultrasev** [comment]
> > > 是否需要先安装cuda toolkit安装包 然后再进行安装呢
> > 
> > 
> > @frisk0926 默认应该已经装好 CUDA 了。
> 
> ![1706924686844](https://private-user-images.githubusercontent.com/129162725/302005706-9cd096af-bb3f-46b6-bf2d-bddf46427c17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MjUyOTUsIm5iZiI6MTcwNjkyNDk5NSwicGF0aCI6Ii8xMjkxNjI3MjUvMzAyMDA1NzA2LTljZDA5NmFmLWJiM2YtNDZiNi1iZjJkLWJkZGY0NjQyN2MxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QwMTQ5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODU4YzljMGM4YTRmY2VlNTNiZWJlYjc5YmY5NzBiNjUxNThmYThmMjYyM2RmNTc5Zjg1YzZkYTdiYTNkYjE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KHhxxSMMK_hnSwgemloghi696cGPGvzuatX9Zu-McjY) y有可能和版本有关吗

@frisk0926 有这个可能，我感觉也有可能你前面 session 失效了，需要重新执行一遍 😀

**Comment by frisk0926** [comment]
> > > > 是否需要先安装cuda toolkit安装包 然后再进行安装呢
> > > 
> > > 
> > > @frisk0926 默认应该已经装好 CUDA 了。
> > 
> > 
> > ![1706924686844](https://private-user-images.githubusercontent.com/129162725/302005706-9cd096af-bb3f-46b6-bf2d-bddf46427c17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MjUyOTUsIm5iZiI6MTcwNjkyNDk5NSwicGF0aCI6Ii8xMjkxNjI3MjUvMzAyMDA1NzA2LTljZDA5NmFmLWJiM2YtNDZiNi1iZjJkLWJkZGY0NjQyN2MxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QwMTQ5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODU4YzljMGM4YTRmY2VlNTNiZWJlYjc5YmY5NzBiNjUxNThmYThmMjYyM2RmNTc5Zjg1YzZkYTdiYTNkYjE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KHhxxSMMK_hnSwgemloghi696cGPGvzuatX9Zu-McjY) y有可能和版本有关吗
> 
> @frisk0926 有这个可能，我感觉也有可能你前面 session 失效了，需要重新执行一遍 😀

貌似只能在cuda 11环境下  我把安装包换成12可以吗

**Comment by ultrasev** [comment]
@frisk0926 试试这个，redis 改成你的 https://www.kaggle.com/code/xiu0714/notebooke81877bb6f/notebook 
<img width="1150" alt="image" src="https://github.com/ultrasev/stream-whisper/assets/51262739/611d8c42-52a4-4379-bf08-85aa87c48a02">

**Comment by frisk0926** [comment]
> @frisk0926 试试这个，redis 改成你的 https://www.kaggle.com/code/xiu0714/notebooke81877bb6f/notebook <img alt="image" width="1150" src="https://private-user-images.githubusercontent.com/51262739/302006669-611d8c42-52a4-4379-bf08-85aa87c48a02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MjYwMjYsIm5iZiI6MTcwNjkyNTcyNiwicGF0aCI6Ii81MTI2MjczOS8zMDIwMDY2NjktNjExZDhjNDItNTJhNC00Mzc5LWJmMDgtODVhYTg3YzQ4YTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDAyMDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YTdhZjgyMmZhNjY3NGJjODdkMjQzMTQwNjdiMDRiOWI0MWRjMTM5MTVmYWVjMDBkYTFlNGQ3Y2FjYjk5NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vc7uIHzWZ1WFqL03wTpImkuFs5g8JWFJ4-q2MXb3-3Q">

好像就是cuda版本的问题，博主可以分享一下你的notebook吗  kaggle重装cuda有点问题 

这是之前视频里用到的 notebook，https://www.kaggle.com/xiu0714/faster-whisper   ， 聊天用到的 pandoranext 已经关停了，我把 chat 部分去掉了。 转写那一块我试了一下，没问题。 
看看能打开吗？

**Comment by ultrasev** [comment]
@frisk0926 搞定没？

**Comment by frisk0926** [comment]
> @frisk0926 搞定没？

用你的notebook可以了   我看看和我的哪里不一样

**Comment by frisk0926** [comment]
> @frisk0926 搞定没？

目前唯一的疑问就是在你的notebook中安装libcublas11 库的时候可以直接安装进去，而新建notebook之后就不能直接安装了，显示Unable to locate package libcublas11，这个问题在网上找了很久没找到

**Comment by ultrasev** [comment]
> > @frisk0926 搞定没？
> 
> 目前唯一的疑问就是在你的notebook中安装libcublas11 库的时候可以直接安装进去，而新建notebook之后就不能直接安装了，显示Unable to locate package libcublas11，这个问题在网上找了很久没找到

@frisk0926 不安装应该也能运行吧，我是遇到了依赖问题才安装的，不过放到文档里确实有点误导。

**Comment by frisk0926** [comment]
> > > @frisk0926 搞定没？
> > 
> > 
> > 目前唯一的疑问就是在你的notebook中安装libcublas11 库的时候可以直接安装进去，而新建notebook之后就不能直接安装了，显示Unable to locate package libcublas11，这个问题在网上找了很久没找到
> 
> @frisk0926 不安装应该也能运行吧，我是遇到了依赖问题才安装的，不过放到文档里确实有点误导。

不安装不能运行，最后一步的时候会报错的，不知道这个依赖库为啥会找不到
![0EFE0AD1](https://github.com/ultrasev/stream-whisper/assets/129162725/423d2bcf-7861-4c14-a49c-a23470245032)

**Comment by frisk0926** [comment]
> > > > @frisk0926 搞定没？
> > > 
> > > 
> > > 目前唯一的疑问就是在你的notebook中安装libcublas11 库的时候可以直接安装进去，而新建notebook之后就不能直接安装了，显示Unable to locate package libcublas11，这个问题在网上找了很久没找到
> > 
> > 
> > @frisk0926 不安装应该也能运行吧，我是遇到了依赖问题才安装的，不过放到文档里确实有点误导。
> 
> 不安装不能运行，最后一步的时候会报错的，不知道这个依赖库为啥会找不到 ![0EFE0AD1](https://private-user-images.githubusercontent.com/129162725/302026847-423d2bcf-7861-4c14-a49c-a23470245032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTM1NDAsIm5iZiI6MTcwNjk1MzI0MCwicGF0aCI6Ii8xMjkxNjI3MjUvMzAyMDI2ODQ3LTQyM2QyYmNmLTc4NjEtNGMxNC1hNDljLWEyMzQ3MDI0NTAzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QwOTQwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjgwYjYzMTI3ZmExMzNmNDM0NDJhMzQ4ZjllMTE3ZjRlOTY2ODJlNjgxMWEyMjkzMGRhNzM0ZGU3YmQ4YTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O1PYYPLAkaCx8wVdICogkBAhSUG5QrzB-lJNN8VDvKE)

在本地运行也麻烦，还不如在kaggle上面全，不知道为啥换了一个notebook上就不能安装了😂 你在安装这个库前还进行了什么操作吗

**Comment by ultrasev** [comment]
@frisk0926 我猜是系统版本不一样，视频里面 ubuntu 22.04 ，新开的是 ubuntu 20.04 
<img width="725" alt="image" src="https://github.com/ultrasev/stream-whisper/assets/51262739/66f9279a-84c8-455c-bf5a-48837ef9bcae">

先拿上面分享的当 base kernel 吧

**Comment by ultrasev** [comment]
据我了解， Google colab 的也是 ubuntu 22.04

**Comment by ultrasev** [comment]
> @frisk0926 我猜是系统版本不一样，视频里面 ubuntu 22.04 ，新开的是 ubuntu 20.04 <img alt="image" width="725" src="https://private-user-images.githubusercontent.com/51262739/302027128-66f9279a-84c8-455c-bf5a-48837ef9bcae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTM2NTYsIm5iZiI6MTcwNjk1MzM1NiwicGF0aCI6Ii81MTI2MjczOS8zMDIwMjcxMjgtNjZmOTI3OWEtODRjOC00NTVjLWJmNWEtNDg4MzdlZjliY2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDA5NDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMTc2YTlhYzRmNjY3MDFhM2ZiNDExNDAzYmU1MjA1MzAyZDI1MDEzZjZlYmY5Zjg1MzEwZjI4MTkxNGNmZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s9TY0Y-1bK1vqkrAtqKw1fHfUQqLJIriIiBZy9EmPvs">
> 
> 先拿上面分享的当 base kernel 吧

@frisk0926 这个随机性比较大，有时候开出来是 22.04 有时候是 20.04，不知道有没有办法控制。

**Comment by frisk0926** [comment]
> > @frisk0926 我猜是系统版本不一样，视频里面 ubuntu 22.04 ，新开的是 ubuntu 20.04 <img alt="image" width="725" src="https://private-user-images.githubusercontent.com/51262739/302027128-66f9279a-84c8-455c-bf5a-48837ef9bcae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTM2NTYsIm5iZiI6MTcwNjk1MzM1NiwicGF0aCI6Ii81MTI2MjczOS8zMDIwMjcxMjgtNjZmOTI3OWEtODRjOC00NTVjLWJmNWEtNDg4MzdlZjliY2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDA5NDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMTc2YTlhYzRmNjY3MDFhM2ZiNDExNDAzYmU1MjA1MzAyZDI1MDEzZjZlYmY5Zjg1MzEwZjI4MTkxNGNmZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s9TY0Y-1bK1vqkrAtqKw1fHfUQqLJIriIiBZy9EmPvs">
> > 先拿上面分享的当 base kernel 吧
> 
> @frisk0926 这个随机性比较大，有时候开出来是 22.04 有时候是 20.04，不知道有没有办法控制。

这个有办法更新吗 在kaggle上

**Comment by ultrasev** [comment]
> > > @frisk0926 我猜是系统版本不一样，视频里面 ubuntu 22.04 ，新开的是 ubuntu 20.04 <img alt="image" width="725" src="https://private-user-images.githubusercontent.com/51262739/302027128-66f9279a-84c8-455c-bf5a-48837ef9bcae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTM2NTYsIm5iZiI6MTcwNjk1MzM1NiwicGF0aCI6Ii81MTI2MjczOS8zMDIwMjcxMjgtNjZmOTI3OWEtODRjOC00NTVjLWJmNWEtNDg4MzdlZjliY2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDA5NDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMTc2YTlhYzRmNjY3MDFhM2ZiNDExNDAzYmU1MjA1MzAyZDI1MDEzZjZlYmY5Zjg1MzEwZjI4MTkxNGNmZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s9TY0Y-1bK1vqkrAtqKw1fHfUQqLJIriIiBZy9EmPvs">
> > > 先拿上面分享的当 base kernel 吧
> > 
> > 
> > @frisk0926 这个随机性比较大，有时候开出来是 22.04 有时候是 20.04，不知道有没有办法控制。
> 
> 这个有办法更新吗 在kaggle上

这个我没有试过，但一般升级比较花时间。 可以试下拿一个 22.04 的当 base kernel ，在它上面改。

**Comment by ultrasev** [comment]
试试这个  @frisk0926 
<img width="767" alt="image" src="https://github.com/ultrasev/stream-whisper/assets/51262739/ff611f6f-0572-41f1-ad65-25f0de74c137">

**Comment by frisk0926** [comment]
> 试试这个 @frisk0926 <img alt="image" width="767" src="https://private-user-images.githubusercontent.com/51262739/302027658-ff611f6f-0572-41f1-ad65-25f0de74c137.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTk5NTQsIm5iZiI6MTcwNjk1OTY1NCwicGF0aCI6Ii81MTI2MjczOS8zMDIwMjc2NTgtZmY2MTFmNmYtMDU3Mi00MWYxLWFkNjUtMjVmMGRlNzRjMTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDExMjczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZGFiNWY5NDE4NDllY2RkOTU5ZTNiMTMyZjkyNTlhNmRjNjRlNjc1NDhhNTI1NzM2ODU0ZjEzZjZkYTA2OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.453kYwftb3zb18RFspzBfVgvoQBzCDY-_6BGEOhbiOc">

确实就是操作系统的问题  升级到最新操作系统之后就能够下载兼容了  但这个依赖确实是必须的 而且是需要libcublas11的版本，我试了下载libcublas10的版本，并不可以，所以需要在ubuntu22.04下下载libcublas11的依赖，才能最后跑的通
